### ISSUE TITLE
Cannot register my server

### ISSUE THREAD

**Issue by Stizzo** [garncarz/nogamespy-vietcong#29]
Hello, I am trying to host my game on vietcong, but it doesn't appears on the server list.
Here is what I have done:
- I modified the host file as described on vietcong1.eu, adding 46.28.109.117 master.gamespy.com
- I mapped port 5425/tcp&udp (I use this port on vc) and 29700/udp (not sure if this last is required).
- I start the server time to time, just when I want to play with friends, but I am evaluating to keep it fix.
- My ip address is static and starts with : 51.154.136.* (please don't publish it completely, since it is also used for some other services).

Is there something missing?
Or is it a bug?
Thanks,
Stizzo

**Comment by garncarz** [comment]
Hello @Stizzo, thanks for reporting. I would look into that by trying to retrieve data from your server manually, but for that I really need full IP. (If it's a public IP, then it can get scanned etc. no matter if you publish its IP somewhere or not. Just don't write down other open ports here.)

When looking into DB, there's no record for any IP like that. (It keeps records for offline servers for 30 minutes, in case they come online again.)

```
>>> models.Server.query.filter(models.Server.ip.startswith('51.154.136')).all()
[]
```

**Comment by Stizzo** [comment]
Thanks @garncarz for your fast reply.
That's okay, my server ip is 51 154 136 **.
Can you kindly confirm that the only port I should map in my router is 5425/tcp&udp?
Is port 29700 necessary? I will continue to do some tests on my side, but it seems everything okay to me :/

EDIT:
Solved, I also mapped the port 15425/tcp&udp and now it works. 
Thanks for your effort again!

**Comment by garncarz** [comment]
@Stizzo Good job making it work. :+1: 

Sorry I haven't read the first post correctly, I've seen two ports mentioned and thought "that's right". So just for clarification:
- 5425 (I think UDP) is a gaming port on a game server.
- 15425/UDP is an infoport on a game server (returns a map being played, players on the server...).
- 28900/TCP is an infoport on a master server (game clients fetch the server list from here).
- 27900/UDP is a port for the heartbeat service on a master server (game servers ping there).

So owners of game servers need to have only 5425 & 15425 open and correctly rerouted. (+ higher numbers in a row if they provide multiple game servers, like 5426 & 15426, 5427 & 15427...)
