### ISSUE TITLE
Smoother refreshing of all servers

### ISSUE THREAD

**Issue by garncarz** [garncarz/nogamespy-vietcong#9]
Now, when refreshing server list (`tasks.refresh_all_servers`), all servers (and players) are set as offline (then those successfully refreshed are set as online again). When there are some servers with slow response / timeout, this processing can take up some time. During that, Vietcong1.eu shows little to no servers. This should be avoided.

One way to do so is add a new column to `server`, like `waiting_for_sync`. It'll be `False` by default, set to `True` in the beginning of `refresh_all_servers`, then set to `False` again if it's pulled successfully. In the end of the task all servers having `waiting_for_sync == True` will be set as offline.

**Comment by TDNeo** [comment]
Hello garncarz,

I am brand new here and looking for someone who can help me with that: I set up a new VC-server at provider i3D. The IP is 31.204.131.72. This server is online an can be found e.g. by QTracker. But not in the public Internat game list. It is also not shown in the game (server list). 

My hosts file has this entry: 

46.28.109.117 master.gamespy.com

Servers are displayed in the game. My server is not displayed.

I hope you can help me with that? 

Thank you very much 
=TD=Neo

**Comment by garncarz** [comment]
Hello Neo,

thanks for reporting this! I've actually made one fix today to the master/heartbeat service, it tended to get stuck before, now it shouldn't be like that. If you try running your server now, is it still being ignored?

Ondra

**Comment by garncarz** [comment]
I'm testing it right now and it happens to me too that the list is sometimes empty. It's related to this very issue and once it's solved (`waiting_for_sync` column added), it should be ok. I hope I can make it tomorrow.

**Comment by sonicpp** [comment]
I am facing one issue right now - server the gaza strip (77.179.223.2:5425)  is not listed on vietcong1.eu, but it is listed on vietcong.tk/serverlist.php. Also direct connect to this server works - why is not this one listed? Is it related to this issue (I can see other 27 servers as usual)

**Comment by garncarz** [comment]
According to logs, there are multiple servers with `UDP timeout` or `connection refused`. I guess their firewalls are at work, they need to whitelist `46.28.109.117`, it scans their `15425` ports quite often.

**Comment by sonicpp** [comment]
Uhm, ok. Btw I can see one player there right now via vietcong1.eu, so your server knows about this one, but is not showing it (so its the same issue - player is shown but not server where he plays - sorry for alarm).

**Comment by TDNeo** [comment]
I will tell this to my provider i3D:

"_According to logs, there are multiple servers with UDP timeout or connection refused. I guess their firewalls are at work, they need to whitelist 46.28.109.117, it scans their 15425 ports quite often._"

Maybe they can solve the problem ... As soon as i receive an answer I will post it here.

**Comment by TDNeo** [comment]
Answer has just arrived from i3D:

_Hi,
There are no inbound or outbound rules in place that block or rate limit traffic towards ports stated for gaming services in the OS, our layer 7 and our layer 3 appliances.
This means that the master servers will be able to connect to the server without issues once traffic hits our border gateway from the internet.

Best regards,_

So we have still the same question: Why is it that the server will not be listed?

Thank you for support
=TD=Neo

**Comment by garncarz** [comment]
@TDNeo Thank you. I've tried manual registration of your IP: is this your server? https://vietcong1.eu/cs/game/server/31.204.131.72

**Comment by TDNeo** [comment]
Yes exactly. Actually name: "Ballerbude"

I also tryd to register manually here: https://vietcong1.eu/en/game/register

No chance. Does not work with any server. It says: "Couldn't connect to the server. "

Same message with any other server beeing online.

**Comment by TDNeo** [comment]
By the way: Do not mistake with other server "=TD=Neo's Ballerbude"
This is my old server at 4Players. Still running an is well listed.

**Comment by garncarz** [comment]
@TDNeo Oh, you're able to use hidden parts of the site, I can see. 😈 https://vietcong1.eu/game/register is obsolete and works no more, so I've removed it from menu. I should probably delete that page totally. 🙂 

Vietcong heartbeat signals work this way: whenever a game server is started or a map is changed, it pings the master server (port 27900 UDP). (I'm not sure, maybe it pings also from time to time.) Those signals work over UDP network protocol, not TCP, so it's not that sure they'll reach the master server. So if your server isn't recognized, it might help to change map (you can change back and forth).

**Comment by TDNeo** [comment]
The link was a hint given by a player-mate. Will never do so again ;-)
So ... i did changed maps on my server several times actually. I have your server crawler in my hosts file:
46.28.109.117		master.gamespy.com

Let's see what will happen ... actually it is still not listed ...

**Comment by TDNeo** [comment]
I found out that the port 27900 UDP is closed on my server:

Host is up (0.0027s latency).

PORT      STATE  SERVICE

27900/udp closed unknown

I just sent an email to my provider ... lets see what they will answer ...

**Comment by garncarz** [comment]
@TDNeo No, no, that port is open on Vietcong1.eu, that's enough. In the heartbeat sense, your game server is actually a client which communicates with the master server.

**Comment by garncarz** [comment]
I have to look more into logs etc., but it's weekend now, Neo. 🌴 🙂

**Comment by TDNeo** [comment]
OK, have a nice weekend. I should also stop now. Of cause its an outgoing port on my server, not incoming ... omg :-)

**Comment by garncarz** [comment]
@TDNeo I can see your server in the list now, it looks like the commit above helped. 🎈

**Comment by garncarz** [comment]
But now I can't see `=TD=Neo's Ballerbude` (`194.97.164.252`) in the list. Neither can I connect to it in the game, so I suppose that server is really offline. Is it correct, @TDNeo?

**Comment by gaza23** [comment]
Hi, 
now it seems to be ok with the server list. i see now permanently my "the gaza strip" server on the list.
pls dont change anything! :)))

**Comment by TDNeo** [comment]
Hi,
great! It's really in the game-list. Have you changed anything concerning the crawler? If not, it took many days to become member in the list ... 

Now your crawler IP must be communicated to others. Otherwise it will not be shown in the list of other players. QTRacker still does not list my server ... I will inform all players I know and ask them to use your IP.

Yes the old =TD=Neo's Ballerbude (194.97.164.252) is offline due to the match yesterday. We wanted to prevent confusion between the two servers. It looks like that I have to close the old server finally. It has hard freeze effects that can't be solved by provider.

Thank you very much for your support. Hope to see you on Ballerbude next Sunday 🙂

**Comment by TDNeo** [comment]
Hi Ondra,

 

the „the gaza strip“ seems tob e offline. Do you have „AZTEC“ running on your server?

 

 

 

Von: gaza23 [mailto:notifications@github.com] 
Gesendet: Montag, 29. Januar 2018 01:12
An: garncarz/nogamespy-vietcong <nogamespy-vietcong@noreply.github.com>
Cc: TDNeo <TDNeo@gmx.de>; Mention <mention@noreply.github.com>
Betreff: Re: [garncarz/nogamespy-vietcong] Smoother refreshing of all servers (#9)

 

Hi,
now it seems to be ok with the server list. i see now permanently my "the gaza strip" server on the list.
pls dont change anything! :)))

**Comment by TDNeo** [comment]
Actually no "the gaza strip"  ... Not important but it is not listed ...

**Comment by gaza23** [comment]
Everything fine, no panic ☺.its just a home server.its availabe mostly from 3pm till 3am.

**Comment by garncarz** [comment]
Glad that it helped. 🙂 There was a change, this commit: 0b9d76a2d65ac53a78971c747b3711d68f60b248.

So I'll close this issue, but feel free to open a new one if something goes wrong.

**Comment by TDNeo** [comment]
Tnx a lot. Hope 2 cu @ Ballerbude :-)

=TD=Neo
